apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-3
  labels:
    app: my-app-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-3
  template:
    metadata:
      labels:
        app: my-app-3
    spec:
      containers:
      - name: debug
        image: debug/simple-express
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
